version: 2
jobs:
  build:
    working_directory: ~/ton_client
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - run:
          command: |
            sudo apt-get update -q
            sudo apt-get install -y zlib1g
            sudo apt-get install -y openssl
      - checkout
      - restore_cache:
          key: ton_client-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            make setup-all
            poetry install coverage
            poetry install codecov
      - save_cache:
          key: ton_client-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"

      - run:
          command: |
            poetry run flake8 ton_client testsuite
      - store_test_results:
          path: flake8-results
      - store_artifacts:
          path: flake8-results
          destination: fr1

      - run:
          command: |
           poetry run pytest testsuite
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

      - run:
          command: |
            poetry run coverage run setup.py test
            poetry run codecov
